### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by Hosstell** [Inkrekai/test-task#1]
- [x] Не правильное отображение даты. 2019-12-09 -> 09.12.2019
- [x] Не правильное отображение количества элементов в списке  

![Peek 2019-12-09 19-07](https://user-images.githubusercontent.com/31948979/70447489-3b55ba00-1ab8-11ea-890e-901390ac6181.gif)

**Comment by Hosstell** [comment]
- [ ] Что-то неведомое происходит с чекбоксами  

![Peek 2019-12-09 19-21](https://user-images.githubusercontent.com/31948979/70448392-bb305400-1ab9-11ea-9bf2-678dd2a94ab6.gif)

**Comment by Fasturtle1** [comment]
Привет, Кирилл. Отличная работа! Есть пара замечаний:  
 - [ ] При выборе всех сотрудников выбираются и те кто уволен. GIF:  
![fired_button](https://user-images.githubusercontent.com/35260551/70528108-db6a1c80-1b66-11ea-9ce9-16b6e6aad892.gif)  
 - [ ] Сбрасывается результат % ставки при определенной последовательности:  
Редактируем % у **строки №1** ->   кликаем по Ставке **строки №2** -> кликаем по Базе **строки №2** -> изменяем Базу **строки №1**  
![error_percent](https://user-images.githubusercontent.com/35260551/70528921-c4c4c500-1b68-11ea-8f58-fef207010e5f.gif)

**Comment by Inkrekai** [comment]
> Привет, Кирилл. Отличная работа! Есть пара замечаний:
> 
> * [ ]  При выборе всех сотрудников выбираются и те кто уволен. GIF:
>   ![fired_button](https://user-images.githubusercontent.com/35260551/70528108-db6a1c80-1b66-11ea-9ce9-16b6e6aad892.gif)
> * [ ]  Сбрасывается результат % ставки при определенной последовательности:
>   Редактируем % у **строки №1** ->   кликаем по Ставке **строки №2** -> кликаем по Базе **строки №2** -> изменяем Базу **строки №1**
>   ![error_percent](https://user-images.githubusercontent.com/35260551/70528921-c4c4c500-1b68-11ea-8f58-fef207010e5f.gif)

Хорошее замечание, без него мой предыдущий коммит имеет ошибку

**Comment by Inkrekai** [comment]
Вроде бы все проблемы решены, на момент коммита `dfe5c8aec18ccefff3cbd26b46cbd9f36c8e0940`
